EFMVC/EFMVC/Models/ErrorViewModel.cs
namespace EFMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EFMVC/EFMVC/Models/Subject.cs
using System.ComponentModel.DataAnnotations;

namespace EFMVC.Models
{
    public class Subject
    {
        [Key]
        public int SubjectId { get; set; }
        public string? SubjectName { get; set; }
        public string SubjectTerm { get; set; }
        public int SubjectCredets { get; set; }

        public List<Teacher> SubjectTeahers { get; set; } = new List<Teacher>();
    }
}

EFMVC/EFMVC/Models/Teacher.cs
using System.ComponentModel.DataAnnotations;

namespace EFMVC.Models
{
    public class Teacher
    {
        [Key]
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string TeacherAdress { get; set; }
        public int TeacherAge { get; set; }

        public Subject Subject { get; set; }


    }
}

EFMVC/EFMVC/Controllers/SubjectController.cs
using EFMVC.Context;
using EFMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EFMVC.Controllers
{
    public class SubjectController : Controller
    {
        MVCContext db;
        public SubjectController(MVCContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            IEnumerable<Subject> subjects = db.Subjects.Select(s => s).ToList();

            return View(subjects);
        }
        public IActionResult Delete(int id)
        {
            Subject subject = db.Subjects.FirstOrDefault(s => s.SubjectId == id);
            if (subject != null)
            {
                db.Remove(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }
        public IActionResult Edit(int id)
        {
            Subject subject = db.Subjects.Find(3);

            subject.SubjectName = "Giym";
            subject.SubjectCredets = 7;
            subject.SubjectTerm = "Summer";

            db.SaveChanges();
            return RedirectToAction("Index");

            return View();
        }
    }
}

EFMVC/EFMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subject</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EFMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EFMVC/EFMVC/Views/Subject/Index.cshtml
@model IEnumerable<EFMVC.Models.Subject>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectTerm)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubjectCredets)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectTerm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectCredets)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SubjectId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SubjectId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SubjectId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>